version: "3.2"
services:
  postgres-db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres/data:/var/lib/postgres/data
    networks:
      - fitmanager-network

  pgadmin-service:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres-db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    networks:
      - fitmanager-network
    ports:
      - "5050:80"

networks:
  fitmanager-network:
    driver: bridge
